[package]
name = "opensprinkler-firmware"
version = "3.0.0"
edition = "2021"

[features]
demo = []

[dependencies]
libc = "0.2.126"
mac_address = "1.1.3"
md5 = "0.7.0"
#mosquitto-client = "0.1.5"
paho-mqtt = "0.11.1"
tracing = "0.1.35"
rocket = { version = "0.4.11"}
system_shutdown = "3.0.0"
nix = { version = "0.24.2", features = ["fs", "reboot"] }
zbus = "2.3.2"
#gpio-cdev = "0.5.1"
rppal = "0.13.1"

[lib]
name = "rs_open_sprinkler"
path = "src/OpenSprinkler.rs"
crate-type = ["cdylib"]
